=head1 NAME

alias_manager (or alias_manager.pl) - manage Sympa aliases

=head1 SYNOPSYS

S<B<alias_manager> B<add> | B<del> I<listname> I<domain>>

=head1 DESCRIPTION

Alias_manager is a program that helps in installing aliases for newly
created lists and deleting aliases for closed lists. 

Is is called by
I<wwsympa.fcgi> via the I<aliaswrapper>. Alias management is performed
by I<wwsympa.fcgi> only if it was setup in I<--CONFDIR--/wwsympa.conf>
(I<sendmail_aliases> configuration parameter).

Administrators using MTA functionalities to manage aliases (ie
virtual_regexp and transport_regexp with postfix) can disable alias
management by setting
I<sendmail_aliases> configuration parameter to B<none>.

=head1 OPTIONS

=over 5

=item B<add> I<listname> I<domain>

Add the set of aliases for the mailing list I<listname> in the
domain I<domain>.

=item B<del> I<listname> I<domain>

Remove the set of aliases for the mailing list I<listname> in the
domain I<domain>.

=back

=head1 FILES

F<--SENDMAIL_ALIASES--> sendmail aliases file.

=head1 MORE DOCUMENTATION

The full documentation in HTML and PostScript formats can be
found in F</usr/share/doc/sympa/html/>. 

The mailing lists (with web archives) can be accessed at
http://listes.cru.fr/wws/lists/informatique/sympa.

=head1 AUTHORS

Serge Aumont
 	Comité Réseau des Universités

Olivier Salaün
 	Comité Réseau des Universités

Contact authors at <sympa-authors@cru.fr>

This manual page was initially written by Jérôme Marant <jerome.marant@IDEALX.org>
for the Debian GNU/Linux system.

=head1 COPYRIGHT

Copyright E<169> 1997,1998,1999,2000,2001 Comité Réseau des Universités

Copyright E<169> 1997,1998,1999 Institut Pasteur & Christophe Wolfhugel

You may distribute this software under the terms of the GNU General
Public License Version 2 (L<http://www.gnu.org/copyleft/gpl.html>)

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts and no Back-Cover Texts.  A
copy of the license can be found under
F</usr/share/common-licenses/FDL>

=head1 BUGS

Report bugs to <sympa-dev@cru.fr>.

=head1 SEE ALSO

L<sympa(1)>, L<sendmail(8)>.



