=head1 NAME

bounced (or bounced.pl) - Mailing List Bounce Processing Daemon for WWSympa

=head1 SYNOPSYS

S<B<bounced> [ B<-F> ] [ B<-d, -dF> ]>

=head1 DESCRIPTION

Bounced is a program which scans permanently the bounce spool and
processes bounces (non-delivery messages), looking or bad addresses.
Bouncing addresses are tagged in database ; last bounce is kept for
each bvouncing address.

List owners will latter access bounces information via WWSympa.

=head1 OPTIONS

These programs follow the usual GNU command line syntax,
with long options starting with two dashes (`-').  A summary of
options is included below.

=over 5

=item B<-F>

Do not detach TTY.

=item B<-d>, B<-dF>

Run the program in a debug mode.

=back

=head1 FILES

F<--CONFDIR--/wwsympa.conf> WWSympa configuration file.

F<--MAILERPROGDIR--/bouncequeue> bounce spooler, referenced from sendmail alias file

F<--SPOOLDIR--/bounce> incoming bounces directory

F<--PIDDIR--/bounced.pid> this file contains the process ID
of F<bounced.pl>.

=head1 MORE DOCUMENTATION

The full documentation in HTML and PostScript formats can be
found in F</usr/share/doc/sympa/html/>. 

The mailing lists (with web archives) can be accessed at
http://listes.cru.fr/wws/lists/informatique/sympa.

=head1 AUTHORS

Serge Aumont
 	Comité Réseau des Universités

Olivier Salaün
 	Comité Réseau des Universités

Contact authors at <sympa-authors@cru.fr>

This manual page was initially written by Jérôme Marant <jerome.marant@IDEALX.org>
for the Debian GNU/Linux system.

=head1 COPYRIGHT

Copyright E<169> 1997,1998,1999,2000,2001 Comité Réseau des Universités

Copyright E<169> 1997,1998,1999 Institut Pasteur & Christophe Wolfhugel

You may distribute this software under the terms of the GNU General
Public License Version 2 (L<http://www.gnu.org/copyleft/gpl.html>)

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts and no Back-Cover Texts.  A
copy of the license can be found under
F</usr/share/common-licenses/FDL>

=head1 BUGS

Report bugs to <sympa-dev@cru.fr>.

=head1 SEE ALSO

L<sympa(8)>, L<archived(8)>, L<mhonarc(1)>, L<wwsympa.conf(5)>.


