# Configuration for Automated release notes.

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: Implemented enhancements
      labels:
        - enhancement
    - title: Fixed bugs
      labels:
        - bug
    - title: Other changes
      labels:
        - '*'
