markdown: kramdown
remote_theme: sympa-community/sympa-pages-theme
exclude:
  - default/
  - doc/
  - po/
  - src/
  - support/
  - t/
  - www/
  - xt/
  - "*.in"
  - configure.ac
  - cpanfile
  - etc_README
  - Makefile.am
include:
  - CONTRIBUTING.md
plugins:
  - jekyll-readme-index
