
# This module is POD-only, but may be converted to a pm if needed. However,
# that shouldn't happen, where implementation-differences should be handled
# in Net::VOOT::* and Sympa::OAuth*

=head1 NAME

Sympa::VOOT::Renater - how to use the VOOT plugin with Renater servers.

=head1 DESCRIPTION

B<First read> L<Net::VOOT::Renater/DETAILS>.

=head1 AUTHORS

=cut
