=encoding utf-8

=head1 NAME

auth.conf -
Configuration of authentication mechanisms for web interface of Sympa

=head1 DESCRIPTION

F<auth.conf> defines authentication mechanisms for web interface of Sympa.

TBD.

=head1 FILES

=over

=item F<$DEFAULTDIR/auth.conf>

Distribution default.  This file should not be edited.

=item F<$SYSCONFDIR/auth.conf>

=item F<$SYSCONFDIR/E<lt>robot nameE<gt>/auth.conf>

Configuration files for site-wide default and each robot.

=back

=head1 SEE ALSO

L<wwsympa(8)>,
L<sympa_soap_server(8)>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

