=encoding utf-8

=head1 NAME

automatic_lists_description.conf -
Description of automatic list creation with web interface

=head1 DESCRIPTION

F<automatic_lists_description.conf> defines criteria to create automatic
lists with web interface.

TBD.

=head1 FILES

=over

=item F<$SYSCONFDIR/families/E<lt>family nameE<gt>/automatic_lists_description.conf>

=item F<$SYSCONFDIR/E<lt>robot nameE<gt>/families/E<lt>family nameE<gt>/automatic_lists_description.conf>

Files describing a family for site-wide default and each robot.

=back

=head1 SEE ALSO

L<wwsympa(8)>,
L<Sympa::Family>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

