=encoding utf-8

=head1 NAME

charset.conf - Configuration file for legacy character set support by Sympa

=head1 DESCRIPTION

In some language environments, legacy encoding (character set) is
preferred for e-mail messages: For example C<iso-2022-jp> in Japanese
language.

F<charset.conf> defines mapping between language context and legacy character
set for service messages sent by Sympa.  If you want to enable legacy character
set support, simply copy sample F<charset.conf> onto configuration
directory:

    # cp $DEFAULTDIR/charset.conf $SYSCONFDIR/charset.conf

And set the C<legacy_character_support_feature> parameter value in
L<F<sympa.conf>|sympa.conf(5)> to C<on>.

=head2 Note

If you are planning to upgrade Sympa earlier than 5.3a.8,
original F<charset.conf> is required to convert shared documents
during upgrade process.

=head1 FILES

=over

=item F<$DEFAULTDIR/charset.conf>

Distribution default.  This file should not be edited.

=item F<$SYSCONFDIR/charset.conf>

Configuration file.

=back

=head1 SEE ALSO

L<sympa.conf(5)>.

=head1 HISTORY

Legacy character set support appeared on Sympa 6.0.

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>
at 16, Mar 2009,
and modified by VERDIN David <david.verdin@cru.fr>
at 27, April 2009.

=cut

