=encoding utf-8

=head1 NAME

crawlers_detection.conf - User agents to be excluded from session management

=head1 DESCRIPTION

F<crawlers_detection.conf> defines user agents to be excluded from session
management by Sympa web interface.

TBD.

=head1 FILES

=over

=item F<$DEFAULTDIR/crawlers_detection.conf>

Distribution default.  This file should not be edited.

=item F<$SYSCONFDIR/E<lt>robot nameE<gt>/crawlers_detection.conf>

Configuration file for each robot.

=back

=head1 SEE ALSO

L<wwsympa(8)>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

