=encoding utf-8

=head1 NAME

nrcpt_by_domain.conf - Grouping factor for SMTP sessions by recipient domains

=head1 DESCRIPTION

F<nrcpt_by_domain.conf> defines limit of the number of recipients for a
particular domain in each session.

TBD.

=head1 FILES

=over

=item F<$DEFAULTDIR/nrcpt_by_domain.conf>

Distribution default.  This files should not be edited.

=item F<$SYSCONFDIR/nrcpt_by_domain.conf>

Configuration file.

=back

=head1 SEE ALSO

L<bulk(8)>,
L<sympa_config(5)>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

