=encoding utf-8

=head1 NAME

sympa.wsdl - Service description of SOAP HTTP interface for Sympa

=head1 DESCRIPTION

F<sympa.wsdl> defines services provided by SOAP HTTP interface for Sympa.

TBD.

=head1 FILES

=over

=item F<$DEFAULTDIR/sympa.wsdl>

Distribution default.  This file should not be edited.

=item F<$SYSCONFDIR/sympa.wsdl>

=item F<$SYSCONFDIR/E<lt>robot nameE<gt>/sympa.wsdl>

Configuration files for site-wide default and each robot.

=back

=head1 SEE ALSO

L<sympa_soap_server(8)>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

