=encoding utf-8

=head1 NAME

topics.conf - Configuration of list topics

=head1 DESCRIPTION

F<topics.conf> defines topics (categories) of the mailing lists.

TBD

=head1 FILES

=over

=item F<$DEFAULTDIR/topics.conf>

Distribution default.  This file should not be edited.

=item F<$SYSCONFDIR/topics.conf>

=item F<$SYSCONFDIR/E<lt>robot nameE<gt>/topics.conf>

Configuration files for site-wide default and each robot.

=back

=head1 SEE ALSO

L<wwsympa(8)>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

