=encoding utf-8

=head1 NAME

trusted_applications.conf -
Defining applications of SOAP HTTP interface for Sympa

=head1 DESCRIPTION

F<trusted_applications.conf> defines applications of SOAP HTTP interface for
Sympa.

TBD.

=head1 FILES

=over

=item F<$SYSCONFDIR/E<lt>robot nameE<gt>/trusted_applications.conf>

Configuration files for each robot.

=back

=head1 SEE ALSO

L<wwsympa(8)>,
L<sympa_soap_server(8)>.

=head1 HISTORY

This document was initially written by IKEDA Soji <ikeda@conversion.co.jp>.

=cut

